/**
 * Snapshot store — persists NarrativeSnapshots generated by the explanation pipeline.
 *
 * Storage strategy (v1):
 *   - In-memory Map, keyed by symbol, is always the live store.
 *   - In development, the store is hydrated from and flushed to
 *     `.data/snapshots.json` at the project root on each read/write.
 *   - In production (Vercel), the in-memory store is ephemeral per cold start.
 *
 * Upgrade path:
 *   Replace readFromDisk / writeToDisk with calls to a database
 *   (e.g. Vercel KV, PlanetScale, Supabase) — the public API is unchanged.
 */

import fs from "fs";
import path from "path";
import type { NarrativeSnapshot } from "@/lib/types/analysis";

// ---------------------------------------------------------------------------
// Storage config
// ---------------------------------------------------------------------------

const IS_DEV = process.env.NODE_ENV === "development";
const DATA_DIR = path.join(process.cwd(), ".data");
const SNAPSHOTS_FILE = path.join(DATA_DIR, "snapshots.json");

/** Max snapshots retained per symbol in the in-memory store. */
const MAX_PER_SYMBOL = 100;

// ---------------------------------------------------------------------------
// In-memory store
// ---------------------------------------------------------------------------

/** symbol → snapshots[], newest first */
const store = new Map<string, NarrativeSnapshot[]>();
let hydrated = false;

// ---------------------------------------------------------------------------
// Disk I/O (development only)
// ---------------------------------------------------------------------------

function readFromDisk(): void {
  if (!IS_DEV) return;
  try {
    if (!fs.existsSync(SNAPSHOTS_FILE)) return;
    const raw = fs.readFileSync(SNAPSHOTS_FILE, "utf-8");
    const all: NarrativeSnapshot[] = JSON.parse(raw);
    store.clear();
    for (const snap of all) {
      const list = store.get(snap.symbol) ?? [];
      list.push(snap);
      store.set(snap.symbol, list);
    }
  } catch (err) {
    console.warn("[snapshot-store] Failed to read from disk:", err);
  }
}

function writeToDisk(): void {
  if (!IS_DEV) return;
  try {
    if (!fs.existsSync(DATA_DIR)) {
      fs.mkdirSync(DATA_DIR, { recursive: true });
    }
    const all: NarrativeSnapshot[] = [...store.values()].flat();
    fs.writeFileSync(SNAPSHOTS_FILE, JSON.stringify(all, null, 2), "utf-8");
  } catch (err) {
    console.warn("[snapshot-store] Failed to write to disk:", err);
  }
}

function ensureHydrated(): void {
  if (hydrated) return;
  readFromDisk();
  hydrated = true;
}

// ---------------------------------------------------------------------------
// ID generation
// ---------------------------------------------------------------------------

function makeId(symbol: string, timestamp: string): string {
  // e.g. "NVDA_2026-03-17T14:32:00.000Z"
  return `${symbol}_${timestamp}`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Persist a new snapshot. Deduplicates by id so re-running the pipeline
 * for the same symbol within the same second is idempotent.
 */
export function storeSnapshot(snapshot: NarrativeSnapshot): void {
  ensureHydrated();

  const list = store.get(snapshot.symbol) ?? [];

  // Deduplicate by id
  if (list.some((s) => s.id === snapshot.id)) {
    return;
  }

  // Prepend newest first, trim to cap
  const updated = [snapshot, ...list].slice(0, MAX_PER_SYMBOL);
  store.set(snapshot.symbol, updated);

  writeToDisk();

  if (IS_DEV) {
    console.log(
      `[snapshot-store] Stored snapshot ${snapshot.id} ` +
      `(${updated.length} total for ${snapshot.symbol})`
    );
  }
}

/**
 * Retrieve all snapshots for a symbol, newest first.
 */
export function getSnapshots(symbol: string): NarrativeSnapshot[] {
  ensureHydrated();
  return store.get(symbol.toUpperCase()) ?? [];
}

/**
 * Retrieve all snapshots across all symbols, newest first.
 */
export function getAllSnapshots(): NarrativeSnapshot[] {
  ensureHydrated();
  return [...store.values()]
    .flat()
    .sort((a, b) => b.timestamp.localeCompare(a.timestamp));
}

/**
 * Build a NarrativeSnapshot from pipeline outputs.
 * Called by runExplanationPipeline() immediately after synthesize().
 * The optional `changes` parameter is populated when a previous snapshot
 * exists and meaningful narrative changes were detected.
 */
export function buildSnapshot(
  symbol: string,
  summary: string,
  confidenceScore: number,
  confidenceLabel: "low" | "medium" | "high",
  reasoningType: NarrativeSnapshot["reasoningType"],
  drivers: Array<{
    canonicalKey: string;
    title: string;
    driverType: "company" | "sector" | "macro";
    strength: number;
    inferenceLevel: "direct" | "supporting";
    evidenceArticleIndices: number[];
  }>,
  articles: NarrativeSnapshot["articles"],
  changes?: {
    changeNarrative: string | null;
    addedDriverChanges: NarrativeSnapshot["addedDriverChanges"];
    removedDriverChanges: NarrativeSnapshot["removedDriverChanges"];
  }
): NarrativeSnapshot {
  const timestamp = new Date().toISOString();
  return {
    id: makeId(symbol, timestamp),
    symbol,
    timestamp,
    summary,
    confidenceScore,
    confidenceLabel,
    reasoningType,
    drivers,
    articles,
    ...changes,
  };
}
