/**
 * Snapshot store — persists NarrativeSnapshots generated by the explanation pipeline.
 *
 * Storage strategy (v2):
 *   Development                        → disk-backed in-memory store (.data/snapshots.json)
 *   Production with UPSTASH_REDIS_*   → Upstash Redis (persistent across cold starts)
 *   Production without UPSTASH_REDIS_* → in-memory fallback (ephemeral, same as v1)
 *
 * Key pattern: snapshots:{SYMBOL} → JSON array, newest first, capped at MAX_PER_SYMBOL_PROD.
 *
 * Public API (all async):
 *   storeSnapshot(snapshot)  → Promise<void>
 *   getSnapshots(symbol)     → Promise<NarrativeSnapshot[]>
 *   getAllSnapshots()         → Promise<NarrativeSnapshot[]>
 *   buildSnapshot(...)       → NarrativeSnapshot   (sync, pure — no I/O)
 */

import fs from "fs";
import path from "path";
import type { NarrativeSnapshot } from "@/lib/types/analysis";

// ---------------------------------------------------------------------------
// Storage config
// ---------------------------------------------------------------------------

const IS_DEV = process.env.NODE_ENV === "development";

/**
 * Use Redis when UPSTASH_REDIS_REST_URL is present.
 * Always false in development — disk fallback keeps local dev credential-free.
 */
const HAS_REDIS =
  !IS_DEV &&
  !!process.env.UPSTASH_REDIS_REST_URL &&
  !!process.env.UPSTASH_REDIS_REST_TOKEN;

const DATA_DIR = path.join(process.cwd(), ".data");
const SNAPSHOTS_FILE = path.join(DATA_DIR, "snapshots.json");

/** Cap per symbol in Redis / in-memory-prod. Dev retains 100. */
const MAX_PER_SYMBOL_PROD = 20;
const MAX_PER_SYMBOL_DEV = 100;

// ---------------------------------------------------------------------------
// Redis client (lazy singleton — only instantiated when HAS_REDIS is true)
// ---------------------------------------------------------------------------

let _redis: import("@upstash/redis").Redis | null = null;

async function getRedis(): Promise<import("@upstash/redis").Redis> {
  if (_redis) return _redis;
  const { Redis } = await import("@upstash/redis");
  _redis = new Redis({
    url: process.env.UPSTASH_REDIS_REST_URL!,
    token: process.env.UPSTASH_REDIS_REST_TOKEN!,
  });
  return _redis;
}

function kvKey(symbol: string): string {
  return `snapshots:${symbol.toUpperCase()}`;
}

// ---------------------------------------------------------------------------
// In-memory store (dev + prod fallback)
// ---------------------------------------------------------------------------

/** symbol → snapshots[], newest first */
const memStore = new Map<string, NarrativeSnapshot[]>();
let hydrated = false;

// ---------------------------------------------------------------------------
// Disk I/O (development only)
// ---------------------------------------------------------------------------

function readFromDisk(): void {
  if (!IS_DEV) return;
  try {
    if (!fs.existsSync(SNAPSHOTS_FILE)) return;
    const raw = fs.readFileSync(SNAPSHOTS_FILE, "utf-8");
    const all: NarrativeSnapshot[] = JSON.parse(raw);
    memStore.clear();
    for (const snap of all) {
      const list = memStore.get(snap.symbol) ?? [];
      list.push(snap);
      memStore.set(snap.symbol, list);
    }
  } catch (err) {
    console.warn("[snapshot-store] Failed to read from disk:", err);
  }
}

function writeToDisk(): void {
  if (!IS_DEV) return;
  try {
    if (!fs.existsSync(DATA_DIR)) {
      fs.mkdirSync(DATA_DIR, { recursive: true });
    }
    const all: NarrativeSnapshot[] = [...memStore.values()].flat();
    fs.writeFileSync(SNAPSHOTS_FILE, JSON.stringify(all, null, 2), "utf-8");
  } catch (err) {
    console.warn("[snapshot-store] Failed to write to disk:", err);
  }
}

function ensureHydrated(): void {
  if (hydrated) return;
  readFromDisk();
  hydrated = true;
}

// ---------------------------------------------------------------------------
// Memory helpers (shared by dev path and prod fallback)
// ---------------------------------------------------------------------------

function storeToMemory(snapshot: NarrativeSnapshot): void {
  ensureHydrated();
  const list = memStore.get(snapshot.symbol) ?? [];
  if (list.some((s) => s.id === snapshot.id)) return;
  const max = IS_DEV ? MAX_PER_SYMBOL_DEV : MAX_PER_SYMBOL_PROD;
  const updated = [snapshot, ...list].slice(0, max);
  memStore.set(snapshot.symbol, updated);
  writeToDisk();
  if (IS_DEV) {
    console.log(
      `[snapshot-store] Stored ${snapshot.id} (${updated.length} total for ${snapshot.symbol})`
    );
  }
}

function getFromMemory(symbol: string): NarrativeSnapshot[] {
  ensureHydrated();
  return memStore.get(symbol.toUpperCase()) ?? [];
}

// ---------------------------------------------------------------------------
// ID generation
// ---------------------------------------------------------------------------

function makeId(symbol: string, timestamp: string): string {
  return `${symbol}_${timestamp}`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Persist a new snapshot. Deduplicates by id so re-running the pipeline
 * for the same symbol within the same second is idempotent.
 */
export async function storeSnapshot(snapshot: NarrativeSnapshot): Promise<void> {
  if (HAS_REDIS) {
    try {
      const redis = await getRedis();
      const key = kvKey(snapshot.symbol);
      const existing = (await redis.get<NarrativeSnapshot[]>(key)) ?? [];
      if (existing.some((s) => s.id === snapshot.id)) return;
      const updated = [snapshot, ...existing].slice(0, MAX_PER_SYMBOL_PROD);
      await redis.set(key, updated);
      console.log(
        `[snapshot-store] Redis: stored ${snapshot.id} (${updated.length} total for ${snapshot.symbol})`
      );
      return;
    } catch (err) {
      console.warn("[snapshot-store] Redis write failed, falling back to memory:", err);
    }
  }

  storeToMemory(snapshot);
}

/**
 * Retrieve all snapshots for a symbol, newest first.
 */
export async function getSnapshots(symbol: string): Promise<NarrativeSnapshot[]> {
  if (HAS_REDIS) {
    try {
      const redis = await getRedis();
      return (await redis.get<NarrativeSnapshot[]>(kvKey(symbol))) ?? [];
    } catch (err) {
      console.warn("[snapshot-store] Redis read failed, falling back to memory:", err);
    }
  }

  return getFromMemory(symbol);
}

/**
 * Retrieve all snapshots across all symbols, newest first.
 */
export async function getAllSnapshots(): Promise<NarrativeSnapshot[]> {
  if (HAS_REDIS) {
    try {
      const redis = await getRedis();
      const keys = await redis.keys("snapshots:*");
      if (keys.length === 0) return [];
      const arrays = await Promise.all(
        keys.map((k) => redis.get<NarrativeSnapshot[]>(k).then((v) => v ?? []))
      );
      return arrays
        .flat()
        .sort((a, b) => b.timestamp.localeCompare(a.timestamp));
    } catch (err) {
      console.warn("[snapshot-store] Redis read failed, falling back to memory:", err);
    }
  }

  ensureHydrated();
  return [...memStore.values()]
    .flat()
    .sort((a, b) => b.timestamp.localeCompare(a.timestamp));
}

/**
 * Build a NarrativeSnapshot from pipeline outputs.
 * Called by runExplanationPipeline() immediately after synthesize().
 * The optional `changes` parameter is populated when a previous snapshot
 * exists and meaningful narrative changes were detected.
 *
 * Pure/sync — no I/O.
 */
export function buildSnapshot(
  symbol: string,
  summary: string,
  confidenceScore: number,
  confidenceLabel: "low" | "medium" | "high",
  reasoningType: NarrativeSnapshot["reasoningType"],
  drivers: Array<{
    canonicalKey: string;
    title: string;
    driverType: "company" | "sector" | "macro";
    strength: number;
    inferenceLevel: "direct" | "supporting";
    evidenceArticleIndices: number[];
  }>,
  articles: NarrativeSnapshot["articles"],
  sourceFingerprint: string,
  changes?: {
    changeNarrative: string | null;
    addedDriverChanges: NarrativeSnapshot["addedDriverChanges"];
    removedDriverChanges: NarrativeSnapshot["removedDriverChanges"];
  }
): NarrativeSnapshot {
  const timestamp = new Date().toISOString();
  return {
    id: makeId(symbol, timestamp),
    symbol,
    timestamp,
    summary,
    confidenceScore,
    confidenceLabel,
    reasoningType,
    drivers,
    articles,
    sourceFingerprint,
    ...changes,
  };
}
